DROP TABLE IF EXISTS users CASCADE;

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(40) UNIQUE NOT NULL,
	password VARCHAR(64) NOT NULL,
	token VARCHAR(32) NOT NULL
);

COMMIT;