DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS resources CASCADE;

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(40) UNIQUE NOT NULL,
	password VARCHAR(64) NOT NULL,
	token VARCHAR(32) NOT NULL
);
CREATE TABLE resources(
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  title VARCHAR(40),
  content TEXT NOT NULL
);

COMMIT;